model: tabpfn
mode: finetune
sampling_strategy: prototype_undersampling
random_seed: 768
valid_set_ratio: 0.3
n_inference_context_samples: 10000
minority_to_majority_ratio: 0.3
model_path: null
device: auto
inference_precision: auto
prototype_backend: cuml
loss_function: cross_entropy
save_checkpoints: false
finetuning:
  learning_rate: 0.000005
  epochs: 10
  batch_size: 1024
  meta_batch_size: 1
